apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mains.ref
spec:
  group: ref
  names:
    kind: Main
    listKind: MainList
    plural: mains
    singular: main
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Main is the Schema for the mains API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MainSpec defines the desired state of Main
          properties:
            config:
              type: string
          required:
          - config
          type: object
        status:
          description: MainStatus defines the observed state of Main
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
