apiVersion: apps/v1
kind: Deployment
metadata:
  name: ref
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ref
  template:
    metadata:
      labels:
        name: ref
    spec:
      serviceAccountName: ref
      containers:
        - name: ref
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - ref
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ref"
